[package]
name = "rerun-video-sink"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { workspace = true }
kornia-image = { workspace = true }
kornia-imgproc = { workspace = true }
kornia-io = { workspace = true }
rerun = { workspace = true }
